### ISSUE TITLE
External dep list

### ISSUE THREAD

**Issue by luzpaz** [amrit3701/FreeCAD-Reinforcement#1]
@amrit3701 great work so far on this addon! So do you mind listing any external deps/libs this addon relies on? We will eventually need to compile a metadata.txt file for this repo for the FC prerequisite checker (https://github.com/FreeCAD/FreeCAD-addons/issues/29). 
Thanks!

**Comment by amrit3701** [comment]
Hi @luzpaz 

Yes, sure. Given below is the list of FreeCAD workbenches and external Python libraries on which my addon depends.
Workbenches = Arch, Part, Sketcher, Draft
Python libs = os, sys, math, PySide
Thanks.
