### ISSUE TITLE
Correction in Nomenclature required in description figure of Beam Reinforcement

### ISSUE THREAD

**Issue by cnirbhay** [amrit3701/FreeCAD-Reinforcement#127]
Correction in Nomenclature required in description figure of Beam Reinforcement as shown below:

![image](https://user-images.githubusercontent.com/22128586/106357005-83254980-6329-11eb-8b25-5f9503578aa0.png)

@amrit3701 @SurajDadral

**Comment by SurajDadral** [comment]
Fixed by @amrit3701 as per commit: https://github.com/amrit3701/FreeCAD-Reinforcement/commit/710416988432328a326920afdede9188d40e5b72
