### ISSUE TITLE
Selection of Rebar-Spacing

### ISSUE THREAD

**Issue by TassiloLiebelt** [amrit3701/FreeCAD-Reinforcement#157]
Hello guys,

I have a question. I can change the amount for a rebar and the spacing changes automatically. The field for the spacing cannot be selected.

Is this behavior normal? I would like to set the spacing and the number should adapt.

thanks 
Tassilo

**Comment by amrit3701** [comment]
Yes, we distribute rebars with Amount or Spacing. By default, `Amount` field is active and `Spacing` field inactive but you change by selecting the Amount or Spacing radio button.

- Rebar distribution with Amount (See Amount radio button is selected)
![image](https://user-images.githubusercontent.com/10414959/124362301-b3af3d80-dc51-11eb-82f6-3896ac13f636.png)

- Rebar distribution with Spacing (See Spacing radio button is selected)
![image](https://user-images.githubusercontent.com/10414959/124362310-bd38a580-dc51-11eb-83ea-1282b90dda33.png)

**Comment by TassiloLiebelt** [comment]
Hey Amrit,

many thanks for your response. I meant the following menu.

![Bildschirmfoto vom 2021-07-03 22-27-46](https://user-images.githubusercontent.com/70227109/124366164-f242f900-dc4d-11eb-895e-291a902d8b05.png)




I ask for the following reason. If I subsequently change the dimensions of a component, a constant spacing and not a constant amount should be maintained

The setting you have calculates from the given distance, the number, which then serves as a reference for the component. 

An idea how I could implement it? Maybe in the py-console with methods? or custom spacing?

Thanks for supporting

**Comment by amrit3701** [comment]
> ![Bildschirmfoto vom 2021-07-03 22-27-46](https://user-images.githubusercontent.com/70227109/124366164-f242f900-dc4d-11eb-895e-291a902d8b05.png)

Yes, this feature is not implemented yet. Current rebar objects not capture if the host (structure) dimensions change. But we have a workaround. After changing the dimensions of structure, you should double click on rebar object from tree view structure, this will opens a rebar dialog, then you just click on `OK` button.

For eg:

1. Double click `LShapeRebar` object.
![image](https://user-images.githubusercontent.com/10414959/124366387-2a0d6900-dc6d-11eb-8154-ff60c18db1f7.png)

2. This will again reopen the rebar's dialog box:
![image](https://user-images.githubusercontent.com/10414959/124366467-bae44480-dc6d-11eb-8199-cbbcc940eaa5.png)

3. Click on `OK` button.

Hope this solves your problem.

**Comment by TassiloLiebelt** [comment]
Thank you. 

Last note before closing the issue. So the spacing attribute cant use actually?

FreeCAD.getDocument('Teset').getObject('Rebar').Spacing = 80 set the spacing to 80mm but does not effect the amount. Looks strange.

**Comment by amrit3701** [comment]
> Last note before closing the issue. So the spacing attribute cant use actually?
> 
> FreeCAD.getDocument('Teset').getObject('Rebar').Spacing = 80 set the spacing to 80mm but does not effect the amount. Looks strange.

Yes, the value of `Spacing` calculates from `Amount`. See https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Arch/ArchRebar.py#L427

But anyway, as I said you can control the `Spacing` of any bar from its rebar dialog.
