### ISSUE TITLE
[ Bug ] Values in dialogs are multiplied if the comma is the decimal separator

### ISSUE THREAD

**Issue by Roy-043** [amrit3701/FreeCAD-Reinforcement#181]
The problem is caused by code like this (occurs in many places):
https://github.com/amrit3701/FreeCAD-Reinforcement/blob/ade0085b3b1dac99afc353d246b903d814240315/ColumnReinforcement/MainColumnReinforcement.py#L135

This result is a value of 4000mm if the comma is used as the decimal separator.

This can be solved as in this PR:
https://github.com/yorikvanhavre/BIM_Workbench/pull/120

Alternatively removing `.00` will also work. But the solution in the referenced PR is better.

**Comment by balrobs** [comment]
Now the „Beam Reinforcement“-dialog is outstandig. Here values are defined in the UI-resource files i.e. „80.0“. I changed the UI-files by deleting the decimal separator but this was not enough. @Roy-043 can you gently advice me how to achieve my goal. Thx in advance

**Comment by Roy-043** [comment]
To avoid the multiplication you can change (for example):

https://github.com/amrit3701/FreeCAD-Reinforcement/blob/ade0085b3b1dac99afc353d246b903d814240315/BeamReinforcement/ShearRebars_HookExtensionEditDialog.py#L48-L61

to:

```python
    def setupUi(self):
        """This function is used to set values in ui."""
        self.connectSignalSlots()
        sets = len(self.HookExtensionTuple)
        for i in range(0, sets):
            self.addSet()
            if self.HookExtensionTuple[i] is None:
                self.HookExtensionInputFieldList[i].setText(
                    FreeCAD.Units.Quantity("40 mm", FreeCAD.Units.Length).UserString
                )
                self.HookExtensionInputFieldList[i].setEnabled(False)
            else:
                self.HookExtensionInputFieldList[i].setText(
                    FreeCAD.Units.Quantity(self.HookExtensionTuple[i], FreeCAD.Units.Length).UserString
                )
                self.HookExtensionInputFieldList[i].setEnabled(True)
```

There are similar functions elsewhere.

But this does not solve how the "Hook Extension" is displayed in the "Beam Reinforcement Dialog Box". This text box will still show values in mm. And the number of decimals can be awkward as well:
`(80.00999999999999, 80.00999999999999, 80.00999999999999)`

Fixing that would require a lot more work I think. The code now uses the `ast` module for conversions. That would have to be abandoned then.

**Comment by balrobs** [comment]
Thank you @Roy-043 
thanks to your help i was able to come to a result despite my limited knowledge. i am very grateful to you for that :-)
