### ISSUE TITLE
Side Cover Property -> Left , Right

### ISSUE THREAD

**Issue by chakkreetiya** [amrit3701/FreeCAD-Reinforcement#2]
I think, "Side Cover Property" should separate to   "Left Side Cover Property" and  "Right Side Cover Property". 
For more detail, link.. [Rebars in continuous beam](https://forum.freecadweb.org/viewtopic.php?f=8&=22760&start=130#p182929)

Regard.

**Comment by amrit3701** [comment]
Discussion: https://forum.freecadweb.org/viewtopic.php?f=8&t=22760&p=183045#p183045

**Comment by amrit3701** [comment]
https://forum.freecadweb.org/viewtopic.php?f=8&t=22760&start=160#p183342
