### ISSUE TITLE
Is Reinforcement WB ready for FreeCAD v1.0 Release ?

### ISSUE THREAD

**Issue by luzpaz** [amrit3701/FreeCAD-Reinforcement#221]
* https://github.com/FreeCAD/FreeCAD-addons/issues/305  

*Please also consider testing this wb with Qt6 and Coin3D v4.0.3 builds since 1.0 release cycle will be oriented to stabilizing those libs within FC*

**Comment by luzpaz** [comment]
bumping

**Comment by amrit3701** [comment]
@luzpaz Circular dependency issue is not anymore. Here is the fix: https://github.com/amrit3701/FreeCAD-Reinforcement/commit/62317582542d80dba15dbae2a02902b7b5fe143e

**Comment by luzpaz** [comment]
What's left to do here ?

**Comment by luzpaz** [comment]
@amrit3701 ping

**Comment by amrit3701** [comment]
@luzpaz Nothing, I already tested the code and it is working with FreeCAD 1.0
