### ISSUE TITLE
[Rebar] This addon needs an SVG icon

### ISSUE THREAD

**Issue by luzpaz** [amrit3701/FreeCAD-Reinforcement#24]
Now that the Addon Manager has been updated, each addon/wb needs an avg to represent it.

**Comment by luzpaz** [comment]
@amrit3701 please respond. 
https://github.com/FreeCAD/FreeCAD/tree/master/src/Mod/AddonManager/Resources/icons

**Comment by amrit3701** [comment]
@luzpaz Thanks for ping me again. I forgot this in my todo list. I will fix it tomorrow. thanks

**Comment by amrit3701** [comment]
Done: https://github.com/FreeCAD/FreeCAD/pull/2408
