### ISSUE TITLE
Updating Reinforcement WB to be compatible with the upcoming 0.18 release (req. py3 and Qt5 compatibility)

### ISSUE THREAD

**Issue by luzpaz** [amrit3701/FreeCAD-Reinforcement#6]
https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by amrit3701** [comment]
Start working of this issue.
FreeCAD forum thread: https://forum.freecadweb.org/viewtopic.php?f=10&t=32307

**Comment by amrit3701** [comment]
Now, rebar addon supports Python3 and Qt5.
