### ISSUE TITLE
Set size of icon in the dialog box.

### ISSUE THREAD

**Issue by amrit3701** [amrit3701/FreeCAD-Reinforcement#7]
On the Qt5, image icon size is normal but on Qt4 it is very large.

**Comment by SurajDadral** [comment]
Can you please share screenshot with Qt4?

**Comment by amrit3701** [comment]
This issue was fixed. Forgot to update it here.

**Comment by amrit3701** [comment]
@SurajDadral You may fix this issue. https://github.com/amrit3701/FreeCAD-Reinforcement/issues/10

**Comment by SurajDadral** [comment]
OK I will look into it.

**Comment by SurajDadral** [comment]
OK I will look into it.

**Comment by SurajDadral** [comment]
This issue has been solved in PR: https://github.com/amrit3701/FreeCAD-Reinforcement/pull/12
