### ISSUE TITLE
Use natural sorting for sorting rebar marks

### ISSUE THREAD

**Issue by SurajDadral** [amrit3701/FreeCAD-Reinforcement#96]
As reported here: https://forum.freecadweb.org/viewtopic.php?f=23&t=44580&start=290#p427807

> In the BOM, rebar-shape-cut-list and bar-bending-schedule rebars ordering is done alphabetically by mark. If all marks have a numerical value it would be nice if they could be ordered numerically too. So mark number 10 comes after 9 and not after 1.

![image](https://user-images.githubusercontent.com/40318315/92141092-9b06a900-ee2f-11ea-8ab7-4ca829b2a348.png)

**Comment by SurajDadral** [comment]
May use: https://github.com/SethMMorton/natsort
OR: https://www.tutorialspoint.com/How-to-correctly-sort-a-string-with-a-number-inside-in-Python

**Comment by Sudhanshu-Dubey14** [comment]
Please assign this to me.

**Comment by amrit3701** [comment]
Fixed! 
PR: https://github.com/amrit3701/FreeCAD-Reinforcement/pull/144
